### ISSUE TITLE
KeyTable setting menu visual fixes

### ISSUE THREAD

**Issue by FeiFei-GH** [FeiFei-GH/Bonkio-Mods#5]
**Describe the bug**
The key text update UI misbehaves under the small window.
The heavy and special text fields are reversed.

**To Reproduce**
1. Click on the HUD button to enter settings menu
2. Scroll down to Keytable and click
3. See error

**Expected behavior**
The UI should just looks like the Keytable Window

**Screenshots**
![image](https://github.com/user-attachments/assets/db3a7512-27e5-4ae3-b72c-136bb76450e6)
![image](https://github.com/user-attachments/assets/2919fce8-f6bd-46de-94b9-2ebdc25bf202)

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser: Chrome
 - Version: BonkLIB 1.1.3, KeyTable 1.4.2

**Additional context**
None

**Comment by Clarifie** [comment]
PR #6
